"""Inclusao de filmes

Revision ID: e9e54be2b7b1
Revises: e5e3b41999c7
Create Date: 2025-09-11 22:22:35.898754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e54be2b7b1'
down_revision = 'e5e3b41999c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Filmes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo_original', sa.String(length=256), nullable=False),
    sa.Column('titulo_nacional', sa.String(length=256), nullable=True),
    sa.Column('ano_lancamento', sa.Integer(), nullable=False),
    sa.Column('lancado', sa.Boolean(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('orcamento', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('faturamento_lancamento', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('poster_principal', sa.Text(), nullable=True),
    sa.Column('link_trailer', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Filmes')
    # ### end Alembic commands ###
